dist: xenial
language: python
python: "3.7"
cache: pip

matrix:
  include:
    - env: FC=gfortran-4.9
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gfortran-4.9

    - env: FC=gfortran-5
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gfortran-5

    - env: FC=gfortran-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gfortran-6

    - env: FC=gfortran-7
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gfortran-7

    - env: FC=gfortran-8
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gfortran-8

  # allowed failures - uncomment lines below to allow failure
  #                    of specific gfortran compilers
  #allow_failures:
  #  - env: FC=gfortran-7
  #  - env: FC=gfortran-8


install:
    - if [[ ! -d "$HOME/.local/bin" ]]; then
        mkdir "$HOME/.local/bin";
      fi
    - export PATH="$HOME/.local/bin:$PATH"
    - ln -fs /usr/bin/$FC "$HOME/.local/bin/gfortran"
    - gfortran --version
    - pip install nose-timer requests numpy matplotlib
    - pip install https://github.com/modflowpy/flopy/zipball/develop
    - pip install https://github.com/modflowpy/pymake/zipball/master


script:
    - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
    - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
    - pwd
    #- git clone https://github.com/MODFLOW-USGS/modflow6-examples.git ../modflow6-examples
    - ls ../
    - which python
    - python --version
    - python -c "import numpy as np; print('numpy version {}'.format(np.__version__))"
    - python -c "import flopy; flopypth = flopy.__path__[0]; print('flopy is installed in {}'.format(flopypth))"
    - python -c "import flopy; dir(flopy.mf6)"
    - cd ./autotest
    - cd ..
    - python -c "import flopy; dir(flopy.mf6)"
    - which nosetests
    - nosetests --version
    - nosetests -v --with-id --with-timer -w ./autotest
