      MODULE MIN_SAT
C
      LOGICAL DOMINSAT,DRYON
      INTEGER, ALLOCATABLE :: ICBND2(:,:,:),ID2D(:)
      REAL, ALLOCATABLE    :: QC7(:,:,:,:,:),C7(:)
      INTEGER ICNTDRY,NCNTDRY,NICBND2
      INTEGER MUTDRY,IC2DRY,IABSMIN,IDRYBUD
      INTEGER IATS
C
      END MODULE MIN_SAT
