      SUBROUTINE FMI1MF6RP1A()
      END SUBROUTINE
      
      SUBROUTINE FMI1MF6RP2A()
      END SUBROUTINE
      
      SUBROUTINE MF6FMINAM(FNAME,IU,IOUT,FILSTAT,FILACT,FMTARG,IFLEN)
        INTEGER IU,IOUT,IFLEN
        CHARACTER*20 FNAME,FILSTAT,FILACT,FMTARG
      END SUBROUTINE