sources = files(
  'adv1.f',
  'btn1.f',
  'cts1.f',
  'dsp1.f',
  'fmi1.f',
  'fmi1mf6.f',
  'gcg1.f',
  'gnt1.f',
  'hss1.f',
  'lkt1.f',
  'mf6bud.f90',
  'mf6grb.f90',
  'mt3d-usgs.f',
  'mt_module.f90',
  'rct1.f',
  'sft1.f',
  'ssm1.f',
  'tob1.f',
  'utl1.f',
  'uzt1.f',
  'xmd1.f',
  'xmdlib1.f',
)

exe = executable(
  buildname,
  sources,
  dependencies: extra_deps,
  install: true
)
